#!/usr/bin/env python3
"""Merge the Cloudflare config generated by `bouncer -g` with the add-on options.

Usage: merge_config.py <generated.yaml> <output.yaml>
Options come from environment variables set by run.sh.

The generated file is the base: it is written by the very bouncer version
that will read the result, so keys this script does not know about (the
`worker` section, `log_mode`, ...) survive unchanged. Only the add-on options
and the zone list are laid over it.

Zones: `-g` silently skips every zone without an A or AAAA record. Behind a
Cloudflare tunnel the hostnames are CNAMEs to the tunnel, so the zone you want
to protect is exactly the one it drops. The zones are therefore also listed
straight from the Cloudflare API with the same token and built the way the
generator builds them (route `*<zone>/*`).
"""
import copy
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

import yaml

CF_API = "https://api.cloudflare.com/client/v4"


def env(name, default=""):
    v = os.environ.get(name, "")
    return v if v not in ("", "null", "[]") else default


def truthy(v):
    return str(v).strip().lower() in ("true", "1", "yes", "on")


def _http_get_json(url, token, timeout=20):
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}",
                                               "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.load(resp)


def list_zones(account_id, token, fetch=_http_get_json):
    """[(zone_id, zone_name)] of active zones in this account the token can see.
    Returns None when the API cannot be asked, so callers can fall back."""
    out, page = [], 1
    try:
        while True:
            q = urllib.parse.urlencode({"account.id": account_id, "status": "active",
                                        "per_page": 50, "page": page})
            data = fetch(f"{CF_API}/zones?{q}", token)
            if not data.get("success"):
                msgs = "; ".join(str(e.get("message")) for e in data.get("errors") or [])
                print(f"[bouncer] Zonenabfrage fehlgeschlagen: {msgs or 'unbekannter Fehler'}", flush=True)
                return None
            for z in data.get("result") or []:
                if z.get("id") and z.get("name"):
                    out.append((str(z["id"]), str(z["name"])))
            info = data.get("result_info") or {}
            if page >= int(info.get("total_pages") or 1):
                return out
            page += 1
    except (urllib.error.URLError, OSError, ValueError) as e:
        print(f"[bouncer] Zonenabfrage fehlgeschlagen: {type(e).__name__}: {e}", flush=True)
        return None


def zone_entry(zone_id, routes, actions, action, captcha, mode):
    return {
        "zone_id": zone_id,
        "actions": list(actions),
        "default_action": action,
        "routes_to_protect": list(routes),
        "turnstile": {
            "enabled": captcha,
            "rotate_secret_key": True,
            "rotate_secret_key_every": "168h0m0s",
            "mode": mode or "managed",
        },
    }


def build(generated, opts, fetch=_http_get_json):
    cf = generated.get("cloudflare_config") or {}
    accounts = cf.get("accounts") or []
    wanted = {z.strip().lower() for z in opts["zones"].split(",") if z.strip()}
    captcha = truthy(opts["captcha_enabled"])
    action = opts["default_action"] or "ban"
    if action == "none":
        action = "ban"          # the Worker only knows ban and captcha; "none" = observe via log_only below
    actions = ["ban"] + (["captcha"] if captcha else [])
    if action == "captcha" and not captcha:
        captcha = True
        actions.append("captcha")

    kept_accounts, names = [], {}
    for acc in accounts:
        token = acc.get("token")
        generated_zones = {str(z.get("zone_id", "")): z for z in acc.get("zones") or [] if z.get("zone_id")}
        api_zones = list_zones(acc.get("id"), token, fetch) if token else None

        candidates = []            # (zone_id, zone_name or "", routes)
        if api_zones is not None:
            for zid, name in api_zones:
                gz = generated_zones.get(zid)
                routes = (gz or {}).get("routes_to_protect") or [f"*{name}/*"]
                candidates.append((zid, name, routes))
                if zid not in generated_zones:
                    print(f"[bouncer] Zone {name} ohne A/AAAA-Eintrag (z. B. hinter einem Tunnel) "
                          f"wird trotzdem geschuetzt: Route *{name}/*", flush=True)
        else:
            for zid, gz in generated_zones.items():
                candidates.append((zid, "", gz.get("routes_to_protect") or []))

        zones = []
        for zid, name, routes in candidates:
            if wanted and zid.lower() not in wanted and name.lower() not in wanted:
                continue
            if not routes:
                continue
            zones.append(zone_entry(zid, routes, actions, action, captcha, opts["captcha_mode"]))
            names[zid] = name
        if zones:
            entry = {k: v for k, v in acc.items() if k != "zones"}
            entry["zones"] = zones
            kept_accounts.append(entry)

    if not kept_accounts:
        raise SystemExit("Keine Zone gefunden, die geschuetzt werden kann. Option 'zones' pruefen "
                         "oder leer lassen, damit alle Zonen des Tokens genommen werden.")

    cfg = copy.deepcopy(generated)
    cs = cfg.setdefault("crowdsec_config", {})
    cs.update({
        "lapi_key": opts["lapi_key"],
        "lapi_url": opts["lapi_url"],
        "update_frequency": opts["update_frequency"] or "10s",
        "only_include_decisions_from": ["cscli", "crowdsec"] if truthy(opts["only_local"]) else [],
    })
    cs.setdefault("include_scenarios_containing", [])
    cs.setdefault("exclude_scenarios_containing", [])

    ccf = cfg.setdefault("cloudflare_config", {})
    ccf["accounts"] = kept_accounts
    if isinstance(ccf.get("worker"), dict):
        ccf["worker"]["log_only"] = (opts["default_action"] == "none")

    cfg["log_level"] = opts["log_level"] or "info"
    if "log_mode" in cfg or "log_media" not in cfg:
        cfg["log_mode"] = "stdout"
        cfg.pop("log_media", None)
    else:
        cfg["log_media"] = "stdout"
    cfg.setdefault("log_dir", "/var/log/")
    prom = cfg.setdefault("prometheus", {})
    prom.update({"enabled": False, "listen_addr": prom.get("listen_addr", "127.0.0.1"),
                 "listen_port": prom.get("listen_port", "2112")})
    cfg["_zone_names"] = names          # stripped again by main(); only for the summary
    return cfg


def summary(cfg):
    names = cfg.get("_zone_names") or {}
    lines = []
    for acc in cfg["cloudflare_config"]["accounts"]:
        zones = ", ".join(names.get(z["zone_id"]) or z["zone_id"] for z in acc["zones"])
        lines.append(f"Konto {acc.get('account_name') or acc.get('id')}: {zones}")
    return lines


def main():
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, encoding="utf-8") as f:
        generated = yaml.safe_load(f) or {}
    opts = {
        "lapi_url": env("LAPI_URL", "http://424ccef4-crowdsec:8080"),
        "lapi_key": env("LAPI_KEY"),
        "default_action": env("DEFAULT_ACTION", "ban"),
        "captcha_enabled": env("CAPTCHA_ENABLED", "false"),
        "captcha_mode": env("CAPTCHA_MODE", "managed"),
        "update_frequency": env("UPDATE_FREQUENCY", "10s"),
        "only_local": env("ONLY_LOCAL", "true"),
        "zones": env("ZONES", ""),
        "log_level": env("LOG_LEVEL", "info"),
    }
    cfg = build(generated, opts)
    lines = summary(cfg)
    cfg.pop("_zone_names", None)
    with open(dst, "w", encoding="utf-8") as f:
        yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
    for line in lines:
        print(f"[bouncer] {line}", flush=True)


if __name__ == "__main__":
    main()
